[package]
name = "msgpack-codec"
version = "0.1.0"
edition = "2024"

[dependencies]
bytes = "1.10.1"
futures = "0.3.31"
rmp = "0.8.14"
rmpv = "1.3.0"
tokio-util = { version = "0.7.16", features = ["codec"] }
